
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: webapp
    spec:
      containers:
      - name: webapp
        image: ghoul007/server
        ports:
        - containerPort: 80
        - containerPort: 443
      imagePullSecrets:
      - name: myregistrykey